# Generated by Django 4.2.10 on 2024-02-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_year', models.IntegerField(default=2000)),
                ('artist', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('download_url', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish')], max_length=20)),
                ('playCount', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
