# Generated by Django 4.2.10 on 2024-02-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='playCount',
            new_name='play_count',
        ),
    ]
