# Generated by Django 4.2.10 on 2024-02-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audify', '0002_rename_playcount_audio_play_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
